version: '2.1'

services:
  rental:
    image: robotron1/quarkus_rental
    mem_limit: 512m
    ports:
      - "8080:8080"

  comment:
    image: robotron1/quarkus_comment
    mem_limit: 512m
    ports:
      - "8080:8080"
  app:
    image: robotron1/quarkus_rental-service
    mem_limit: 512m
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:5.0.9
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
